config/routes.rb
Rails.application.routes.draw do
  devise_for :admins
  devise_for :users
  root 'static_pages#home'

  resources :restaurants do 
    resources :images
    resources :comments
  end

  resources :users do 
    resources :avatars, only: [:create]
  end

 
resources :restaurants do
  resources :reservations
end

resources :favorites, only: [:create , :destroy]

  resources :admins, only: [:show, :index, :create, :edit, :update, :destroy] 
  resources :cities
 
  get '/home', to: 'static_pages#home'
  get '/concept', to: 'static_pages#concept'
  get '/team', to: 'static_pages#team'
  get '/contact', to: 'static_pages#contact'




  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/admin.rb
class Admin < ApplicationRecord
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

         validates :email, presence: true, uniqueness: true, format: { with: /\A[^@\s]+@([^@\s]+\.)+[^@\s]+\z/, message: "Entrez une adresse email valide." }
        
         has_many :restaurants 
         has_many :reservations, through: :restaurants 
         
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/city.rb
class City < ApplicationRecord
    has_many :restaurants
    validates :city_name, presence: true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :restaurant
  belongs_to :user
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :restaurant
  validates :user_id, uniqueness: {scope: 'restaurant_id'}
end

app/models/reservation.rb
class Reservation < ApplicationRecord
  belongs_to :restaurant
  belongs_to :user


  validates :number, presence: true
  validates :date, presence: true
  validates :time, presence: true


end

app/models/restaurant.rb
class Restaurant < ApplicationRecord
    belongs_to :admin
    has_many :favorites, dependent: :destroy

    validates :restaurant_name, presence: true

    belongs_to :admin
    has_one_attached :image
    has_many :comments
    has_many :reservations
    belongs_to :city

    validates :city, presence: true
  end

app/models/user.rb
class User < ApplicationRecord
  
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

    validates :email, presence: true, uniqueness: true, format: { with: /\A[^@\s]+@([^@\s]+\.)+[^@\s]+\z/, message: "Entrez une adresse email valide." }

     has_one_attached :avatar
     has_many :comments
     has_many :reservations, dependent: :destroy
     has_many :favorites, dependent: :destroy
     after_create :welcome_send

     def welcome_send
       UserMailer.welcome_email(self).deliver_now
     end
     



end

app/controllers/admins/restaurants_controller.rb
class Admins::RestaurantsController < ApplicationController
    before_action :authorized?

    def index
      @restaurants = Item.all
    end
    
    def show 
      @restaurant = Item.find(params[:id])
    end
    

    
    def new
      @restaurants = Item.all
      @restaurant = Item.new
    end

    def create
        @restaurant= Restaurant.new(params[:id])
        if @restaurant.save
            redirect_to @restaurant, notice: "Le restaurant a été créé avec succès."
        else
          render :new
        end
      end
end

app/controllers/admins_controller.rb
class AdminsController < ApplicationController
  def new
    @admin = Admin.new
    @restaurant = Restaurant.new
  end

  def show
    @admin = current_admin
    @reservations = @admin.reservations #adminReservation
  end

  def edit
  end

  def create
    @admin = Admin.create(admin_params)
  
      respond_to do |format|
        if @admin.save
          format.html { redirect_to admin_url(@admin), notice: "Le compte professionnel a été créé." }
          format.json { render :show, status: :created, location: @admin }
        else
          format.html { render :new, status: :unprocessable_entity }
          format.json { render json: @admin.errors, status: :unprocessable_entity }
        end
      end
    end

    def update
      @admin = Admin.find(params[:id])
      if @admin.update(admin_params)
        flash[:notice] = "Le compte a bien été mis à jour."
        redirect_to admin_path(current_admin)
      else
        render :edit
      end
    end

  def destroy
  end

  private
  def admin_params
    params.require(:admin).permit(:first_name, :last_name, :city)
  end
end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController
  before_action :authorize_admin, only: [:destroy]

  def index
    @restaurants = Restaurant.all
    # .joins joins restaurant to city
    # .where find all restaurants associated to a city_name = params[:city](value in filter)
    @restaurants = @restaurants.joins(:city).where(cities: { city_name: params[:city] }) if params[:city].present?
  end

  def show
    @restaurant = Restaurant.find(params[:id])
    @comment = @restaurant.comments
    @reservation = Reservation.new
  end

  def new
    @admin = current_admin
    @restaurant = Restaurant.new
  end

  def create
    @restaurant = Restaurant.new(restaurant_params)
    @restaurant.admin = current_admin
    if @restaurant.save
      redirect_to root_path, notice: "Le restaurant a été créé avec succès."
    else
      render :new
    end
  end

  def destroy
    @restaurant = Restaurant.find(params[:id])
    @restaurant.delete
    redirect_to root_path
  end

  def update
    @restaurant = Restaurant.find(params[:id])
    if @restaurant.update(restaurant_params)
      redirect_to @restaurant, notice: 'Le restaurant a été mis à jour.'
    else
      render :edit
    end
  end

  
  private
  def restaurant_params
    params.require(:restaurant).permit(:restaurant_name, :city_id , :image)
  end

  def authorize_admin
    @restaurant = Restaurant.find(params[:id])
    unless current_admin == @restaurant.admin
      redirect_to root_path
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index

  end
  
  def new
    @user = User.new
  end
  
  def show
    @user = current_user
    @reservations = @user.reservations
  end

  def create
  @user = User.create(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to user_url(@user), notice: "Le compte client a été créé." }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      flash[:notice] = "Votre compte a été mis à jour."
      redirect_to user_path(current_user)
    else
      render :edit
    end
  end


  private
  def user_params
    params.require(:user).permit(:first_name, :last_name, :city)
  end
end

app/helpers/admin_session_helper.rb
module AdminSessionHelper
end

app/helpers/admins/restaurants_helper.rb
module Admins::RestaurantsHelper
end

app/helpers/admins_helper.rb
module AdminsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/avatars_helper.rb
module AvatarsHelper
end

app/helpers/cities_helper.rb
module CitiesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/images_helper.rb
module ImagesHelper
end

app/helpers/reservations_helper.rb
module ReservationsHelper
end

app/helpers/restaurants_helper.rb
module RestaurantsHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/restaurants/index.html.erb
<% content_for :title, "Liste des restaurants" %>

<h1 class="h1-resto">QU'EST-CE QU'ON MANGE AUJOURD'HUI ?</h1>
<p class="p-resto"> Venez et découvrez les menus à jour de vos restaurants préférés ! Grâce à Menu, vous saurez toujours ce qu'il se passe en cuisine !</p>

<div class="form-filter d-flex mt-5 ms-4">
  <%= form_tag restaurants_path, method: :get do %>
    <%= label_tag :city, "Choisis ta ville :", class: "text-filter" %>
    <%= select_tag :city, options_for_select([["Aucune ville", ""]] + City.pluck(:city_name), params[:city]), class: "text-filter", id: "select-filter" %> <%# .pluck return all the value of column city_name from table city %>
    <%= submit_tag "Filtrer", class:"btn btn-up-show" %>
  <% end %>
</div>

<div class="row-resto d-flex justify-content-around flex-wrap">
  <% @restaurants.each do |restaurant| %>
    <article class="card">
      <div class="card-img-resto d-flex flex-wrap">
        <%= image_tag "food 2.avif", class: "card-img-resto mb-2", alt: "Photo de couverture du restaurant" %>
      </div>

      <div class="project-info d-flex flex-wrap">
        <div class="flex justify-content-center">
          <div class="project-title"> <%= restaurant.restaurant_name %> </div>
        </div>
        <span class="lighter">
          Venez découvrir l'univers de notre restaurant ! Cliquez pour découvrir notre menu et nos informations.
          <%= link_to restaurant do %>
            <button class="button-card"> Découvrir </button>
          <% end %>
        </span>
      </div>
    </article>
  <% end %>
</div>

<div class="btt">
  <a href="#">
    <button class="button-btt">
      <svg class="svgIcon" viewBox="0 0 384 512">
        <path d="M214.6 41.4c-12.5-12.5-32.8-12.5-45.3 0l-160 160c-12.5 12.5-12.5 32.8 0 45.3s32.8 12.5 45.3 0L160 141.2V448c0 17.7 14.3 32 32 32s32-14.3 32-32V141.2L329.4 246.6c12.5 12.5 32.8 12.5 45.3 0s12.5-32.8 0-45.3l-160-160z"></path>
      </svg>
    </button>
  </a>
</div>

app/views/restaurants/new.html.erb
<% content_for :title, "Création de restaurant" %>

<h1 class="h1-resto">FORMULAIRE DE CRÉATION DE RESTAURANT</h1>

<div class="form-add-resto my-5 mx-5 p-4">
  <%= form_with model: @restaurant, url: restaurants_path, method: "post", html: {multipart: true} do |form| %>
    <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">

    <div class="form-group mb-3 mt-3 col-sm">
      <%= form.label :restaurant_name, 'Nom du restaurant', class: "text-edit" %>
      <%= form.text_field :restaurant_name, class:"form-control-add-resto" %>
    </div>

    <div class="field">
      <%= form.label :city_id, "Ville", class: "text-edit" %>
      <%= form.collection_select :city_id, City.all, :id, :city_name, prompt: "Choisis ta ville", class:"text-edit" %>
    </div>

    <div class="form-group mb-3 mt-3 col-sm">
      <%= form.label :image, 'Photo', class: "text-edit" %>
      <%= form.file_field :image, class:"form-control-add-resto text-edit" %>
    </div>

    <div class="actions text-center">
      <%= form.submit "Ajouter", class:"btn btn-success mt-3 btn-add-resto"%>
    </div>
  <% end %>
</div>


<div class="btt">
  <a href="#">
    <button class="button-btt">
      <svg class="svgIcon" viewBox="0 0 384 512">
        <path d="M214.6 41.4c-12.5-12.5-32.8-12.5-45.3 0l-160 160c-12.5 12.5-12.5 32.8 0 45.3s32.8 12.5 45.3 0L160 141.2V448c0 17.7 14.3 32 32 32s32-14.3 32-32V141.2L329.4 246.6c12.5 12.5 32.8 12.5 45.3 0s12.5-32.8 0-45.3l-160-160z"></path>
      </svg>
    </button>
  </a>
</div>

app/views/restaurants/show.html.erb
<% content_for :title, "Le restaurant" %>

<h1 class="h1-resto"><%= @restaurant.restaurant_name %></h1>
<p class="p-resto"><%= @restaurant.city.city_name %></p>

<div class="show-content d-flex justify-content-around flex-wrap">
  <section class="menu-img flex mx-4 my-4">
    <% if @restaurant.image.attached? %>
      <%= image_tag @restaurant.image, alt: 'Photo du menu du restaurant', class:"image_tag_upld" %>
    <% else %>
      <p class="p-contact"> PAS ENCORE DE MENU </p>
    <% end %>
  </section>

  <section class="infos-resto flex mx-4 my-4"">
    <div class="card-infos card-5 p-3">
      <p class="card__exit">※</p>
      <div class="text-edit mb-4">
        Bienvenue chez <strong> <%= @restaurant.restaurant_name %> </strong> !
        Voici notre menu à jour.
      </div>

      <% if current_user %>
        <div class="form-resa mt-4">
          <%= form_with(model: [@restaurant, @reservation], url: restaurant_reservations_path(@restaurant), method: :post) do |form| %>
            <div class="field">
              <%= form.label "Nombre de personnes", class:"text-edit" %>
              <%= form.number_field :number, min: 1, max: 10, class: "form-control-edit text-edit" %>
            </div>
            
            <div class="field">
              <%= form.label :date, class:"text-edit mt-2" %>
              <%= form.date_field :date, class: "form-control-edit text-edit" %>
            </div>
          
            <div class="field mt-2">
              <%= form.label "Horaire", class:"text-edit" %>
              <%= form.time_field :time, class: "form-control-edit text-edit" %>
            </div>
          
            <%= form.submit "RÉSERVER UNE TABLE", class: "btn btn-book-show mt-4" %>
          <% end %>
        </div>
      <% end %>
    </div>
  </section>
</div>

  <div class="upload-img mx-4">
    <% if current_admin == @restaurant.admin %>
      <%= form_tag restaurant_images_path(@restaurant), multipart: true do %>
        <%= file_field_tag :image, class:"btn mt-3 btn-up-show" %>
        <%= submit_tag "TÉLÉCHARGER", class:"btn mt-3 btn-up-show" %>
      <% end %>

      <%= form_with(model: [:id, @restaurant], local: true, url: restaurant_path, method: "delete") do |form| %>
        <%= form.submit "Supprimer le restaurant", class: "btn mt-3 btn-del-show" %>
      <% end %>
    <% end %>
  </div>

  <% if current_user %>
    <div class="fav-box mx-5">
      <%= button_to "Ajouter aux favoris", favorites_path, params: {favorite: {restaurant_id: @restaurant.id}}, method: :post, class:"btn btn-add-fav" %>
    </div>
  <% end %>

  <section class="mt-5 mx-4">
    <h2>Commentaires</h2>
      <% @comment.each do |comment| %>
        <div class="comment-user p-2 mb-2">
          <p class="text-edit"> <%= comment.user.email %> : " <%= comment.body %> " </p>
          <% if current_user == comment.user %>
            <%= button_to "Supprimer", restaurant_comment_path(@restaurant, comment), method: :delete, class: "btn btn-cancel p-2 mt-0 mb-2", form: { data: { turbo_confirm: "Are you sure?" } } %>
          <% end %>
        </div>
      <% end %>

    <% if current_user %>
      <%= render partial: "comments/form", locals: { restaurant: @restaurant } %>
    <% end %>
  </section>

  <div class="btt">
    <a href="#">
      <button class="button-btt">
        <svg class="svgIcon" viewBox="0 0 384 512">
          <path d="M214.6 41.4c-12.5-12.5-32.8-12.5-45.3 0l-160 160c-12.5 12.5-12.5 32.8 0 45.3s32.8 12.5 45.3 0L160 141.2V448c0 17.7 14.3 32 32 32s32-14.3 32-32V141.2L329.4 246.6c12.5 12.5 32.8 12.5 45.3 0s12.5-32.8 0-45.3l-160-160z"></path>
        </svg>
      </button>
    </a>
  </div>