config/routes.rb
Rails.application.routes.draw do
  devise_for :admins
  devise_for :users
  root 'static_pages#home'

  resources :restaurants do 
    resources :images
    resources :comments
  end

  resources :users do 
    resources :avatars, only: [:create]
  end

 
resources :restaurants do
  resources :reservations
end

resources :favorites, only: [:create , :destroy]

  resources :admins, only: [:show, :index, :create, :edit, :update, :destroy] 
  resources :cities
 
  get '/home', to: 'static_pages#home'
  get '/concept', to: 'static_pages#concept'
  get '/team', to: 'static_pages#team'
  get '/contact', to: 'static_pages#contact'




  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/admin.rb
class Admin < ApplicationRecord
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

         validates :email, presence: true, uniqueness: true, format: { with: /\A[^@\s]+@([^@\s]+\.)+[^@\s]+\z/, message: "Entrez une adresse email valide." }
        
         has_many :restaurants 
         has_many :reservations, through: :restaurants 
         
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/city.rb
class City < ApplicationRecord
    has_many :restaurants
    validates :city_name, presence: true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :restaurant
  belongs_to :user
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :restaurant
  validates :user_id, uniqueness: {scope: 'restaurant_id'}
end

app/models/reservation.rb
class Reservation < ApplicationRecord
  belongs_to :restaurant
  belongs_to :user


  validates :number, presence: true
  validates :date, presence: true
  validates :time, presence: true


end

app/models/restaurant.rb
class Restaurant < ApplicationRecord
    belongs_to :admin
    has_many :favorites, dependent: :destroy

    validates :restaurant_name, presence: true

    belongs_to :admin
    has_one_attached :image
    has_many :comments
    has_many :reservations
    belongs_to :city

    validates :city, presence: true
  end

app/models/user.rb
class User < ApplicationRecord
  
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

    validates :email, presence: true, uniqueness: true, format: { with: /\A[^@\s]+@([^@\s]+\.)+[^@\s]+\z/, message: "Entrez une adresse email valide." }

     has_one_attached :avatar
     has_many :comments
     has_many :reservations, dependent: :destroy
     has_many :favorites, dependent: :destroy
     after_create :welcome_send

     def welcome_send
       UserMailer.welcome_email(self).deliver_now
     end
     



end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index

  end
  
  def new
    @user = User.new
  end
  
  def show
    @user = current_user
    @reservations = @user.reservations
  end

  def create
  @user = User.create(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to user_url(@user), notice: "Le compte client a été créé." }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      flash[:notice] = "Votre compte a été mis à jour."
      redirect_to user_path(current_user)
    else
      render :edit
    end
  end


  private
  def user_params
    params.require(:user).permit(:first_name, :last_name, :city)
  end
end

app/helpers/admins_helper.rb
module AdminsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/avatars_helper.rb
module AvatarsHelper
end

app/helpers/cities_helper.rb
module CitiesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/images_helper.rb
module ImagesHelper
end

app/helpers/reservations_helper.rb
module ReservationsHelper
end

app/helpers/restaurants_helper.rb
module RestaurantsHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/admins/destroy.html.erb
<h1>Admins#destroy</h1>
<p>Find me in app/views/admins/destroy.html.erb</p>

app/views/admins/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation" data-turbo-cache="false">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/admins/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= button_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider), data: { turbo: false } %><br />
  <% end %>
<% end %>

app/views/admins/show.html.erb
<% content_for :title, "Espace professionel" %>

<h1 class="h1-resto"> BIENVENUE DANS VOTRE ESPACE PROFESSIONNEL </h1>

<div class="admin-prof">
      <div class="profile-card">
        <div class="photo-profil">
          <%= image_tag "profil.png" , alt: "Photo de profil" %> 
        </div>

        <div class="input-container-profile <%= 'active' if @admin.email.present? %>">
            <label for="input" class="label-profile">Email</label>
            <input type="text" id="input" required="" readonly value="<%= @admin.email %>">
            <div class="underline"></div>
        </div>

        <div class="btn-edit-container">
          <%= link_to 'Editer profil' , edit_admin_registration_path, class:"btn btn-edit" %>
        </div>
      </div>
  </div>
</div>

<div class="ag-courses_item d-flex justify-content-center">
  <a class="ag-courses-item_link" href="<%= new_restaurant_path %>">
    <div class="ag-courses-item_bg"></div>
    <div class="ag-courses-item_title">
      AJOUTER MON RESTAURANT
    </div>
    <div class="ag-courses-item_date-box">
      <i class="far fa-plus-square text-center mr-2 card-img-top" style="font-size: 50px; color: #f36c01"></i>
    </div>
  </a>
</div>
 
<h3 class="h3-edit">RÉSERVATIONS DANS VOTRE ÉTABLISSEMENT</h3>

<% @reservations.each do |reservation| %>
  <p>Réservation par <%= reservation.user.email %> pour <%= reservation.number %> personnes, le <%= reservation.date.strftime("%d/%m/%Y") %> à <%= reservation.time.strftime("%H:%M") %></p>
  <%= button_to "Supprimer", restaurant_reservation_path(reservation.restaurant, reservation), method: :delete, data: { confirm: "Êtes-vous sûr de vouloir supprimer cette réservation ?" }, class: "btn btn-danger" %>
<% end %>







<div class="btt">
  <a href="#">
    <button class="button-btt">
      <svg class="svgIcon" viewBox="0 0 384 512">
        <path d="M214.6 41.4c-12.5-12.5-32.8-12.5-45.3 0l-160 160c-12.5 12.5-12.5 32.8 0 45.3s32.8 12.5 45.3 0L160 141.2V448c0 17.7 14.3 32 32 32s32-14.3 32-32V141.2L329.4 246.6c12.5 12.5 32.8 12.5 45.3 0s12.5-32.8 0-45.3l-160-160z"></path>
      </svg>
    </button>
  </a>
</div>

app/views/home/_footer.html.erb
<div class="footer-middle">
  <div class="container-footer">

    <div class="middle-logo">
      <div class="logo-section">
        <%= image_tag "LOGO_transparent.png", alt: "logo menu" %>
      </div>

      <br>

        <h4>
          <%= link_to 'RESTAURATEURS ?', new_admin_registration_path, class: "cta-middle" %>
        </h4>
    </div>

    <br>

    <div class="row links-to"> 
      <div class="col-md-4 col-sm-6 footer-link">
        <div class="footer-pad">
          <h5> <%= link_to 'CONCEPT', concept_path, class: "foot-link" %> </h5>
        </div>
      </div>

      <div class="col-md-4 col-sm-6 footer-link">
        <div class="footer-pad">
          <h5> <%= link_to 'TEAM', team_path , class: "foot-link" %> </h5>
        </div>
      </div>

      <div class="col-md-4 col-sm-6 footer-link"> 
        <div class="footer-pad">
          <h5> <%= link_to 'CONTACT', contact_path , class: "foot-link" %> </h5>
        </div>
      </div>
    </div>

    <br>

    <div class="social-icons">
      <div class="social-links">
        <a href="https://www.instagram.com"> <i class="fa-brands fa-instagram fa-2x"></i> </a>
        <a href="https://www.facebook.com"> <i class="fa-brands fa-facebook fa-2x"></i> </a>
        <a href="https://twitter.com"> <i class="fa-brands fa-x-twitter fa-2x"></i> </a>
        <a href="https://play.google.com"> <i class="fa-brands fa-google-play fa-2x"></i> </a>
        <a href="https://www.apple.com"> <i class="fa-brands fa-app-store fa-2x"></i> </a>
      </div>
    </div>

    <div class="row copyright-p">
      <div class="col-md-12 copy text-center mx-auto copyright-section">
        <p class="copyright-thp">MENU © THP - Hiver 2024</p>
      </div>
    </div>
  </div>
</div>

app/views/home/_navbar.html.erb
<div class="container">
  <header class="d-flex justify-content-between py-3 flex-wrap">
    <ul class="nav">
      <li class="nav-item"><%= link_to "RESTAURANTS", restaurants_path, class: "navnav nav-link navbar-text navbar-text-lg" %></li>
    </ul>
   
    <ul class="nav">
      <li class="nav-item">
        <%= link_to image_tag("LOGO_2.png", alt: "Logo", class: "navnav navbar-brand img-fluid logo-img"), root_path, class: "nav-link" %>
      </li>
    </ul>
    
    <% if user_signed_in? || admin_signed_in? %>
      <div class="btn-group">
        <a class="dropdown-toggle navnav-out navbar-text navbar-text-lg-out" type="button" data-bs-toggle="dropdown" aria-expanded="false">
          <% if current_admin %>
            MON ESPACE PRO
          <% elsif current_user %>
            MON ESPACE CLIENT
          <% end %>
        </a>

        <ul class="dropdown-menu">
          <li class="nav-item">
            <% if current_admin %>
              <%= link_to "MON ESPACE PRO", admin_path(current_admin), class: "navnav-hover navbar-text" %>
            <% elsif current_user %>
              <%= link_to "MON ESPACE CLIENT", user_path(current_user), class: "navnav-hover navbar-text" %>
            <% end %>
          </li>

          <li class="nav-item">
            <% if current_admin %>
              <%= link_to "ÉDITER INFOS", edit_admin_registration_path, class: "navnav-hover navbar-text" %>
            <% elsif current_user %>
              <%= link_to "ÉDITER INFOS", edit_user_registration_path, class: "navnav-hover navbar-text" %>
            <% end %>
          </li>

          <li class="nav-item">
            <% if current_admin %>
              <%= button_to "DÉCONNEXION", destroy_admin_session_path, class: "navnav-out navbar-text btn-logout", method: :delete, data: {turbo_method: :delete} %>
            <% elsif current_user %>
              <%= button_to "DÉCONNEXION", destroy_user_session_path, class: "navnav-out navbar-text btn-logout", method: :delete, data: {turbo_method: :delete} %>
            <% end %>
          </li>
        </ul>
      </div>

    <% else %>
      <ul class="nav">
        <li class="nav-item">
          <a class="dropdown-toggle navnav nav-link navbar-text navbar-text-lg" type="button" data-bs-toggle="dropdown" aria-expanded="false">
            SE CONNECTER
          </a>

          <ul class="dropdown-menu">
            <li class="nav-item">
              <%= link_to "CLIENT", new_user_session_path , class: "navnav-hover navbar-text navbar-text-sm" %>
            </li>
            <li class="nav-item">
              <%= link_to "PROFESSIONNEL", new_admin_session_path , class: "navnav-hover navbar-text navbar-text-sm" %>
            </li>
          </ul>
        </li>
      </ul>
    <% end %>
  </header>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title> <%= yield :title %> | MENU </title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Expletus+Sans:ital,wght@0,400..700;1,400..700&family=Raleway:ital,wght@0,100..900;1,100..900&display=swap" rel="stylesheet">
    <script src="https://kit.fontawesome.com/bbd9542c48.js" crossorigin="anonymous"></script>
    <script src="//cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <%= javascript_include_tag 'opendys' %>
    <%= javascript_include_tag 'hide-password' %>
  </head>

  <body data-turbo="false">
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>

    <%= render 'home/navbar' %>
    <%= link_to image_tag("DYS.png", alt: "Bouton pour activer OpenDyslexic", style: "width: 60px; height: 60px;"), "#", id: "toggle-opendys", onclick: "toggleOpenDyslexic();" %>


    <%= yield %>

    <%= render 'home/footer' %>
    
  
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
  </body>
</html>